import React, { useState } from 'react';
import { AppConfig, AppStatus, BuildLog, GeneratedAsset } from './types';
import ConfigurationPanel from './components/ConfigurationPanel';
import MobilePreview from './components/MobilePreview';
import BuildTerminal from './components/BuildTerminal';
import { generateAppCode } from './services/geminiService';
import { Code, Download, Smartphone, Zap, AlertTriangle, X } from 'lucide-react';

const initialConfig: AppConfig = {
  appName: '',
  packageName: '',
  description: '',
  primaryColor: '#10b981',
  features: [],
  category: 'General'
};

const App: React.FC = () => {
  const [config, setConfig] = useState<AppConfig>(initialConfig);
  const [status, setStatus] = useState<AppStatus>(AppStatus.IDLE);
  const [logs, setLogs] = useState<BuildLog[]>([]);
  const [generatedFiles, setGeneratedFiles] = useState<GeneratedAsset[]>([]);
  const [activeTab, setActiveTab] = useState<'preview' | 'code'>('preview');
  const [showApkAlert, setShowApkAlert] = useState(false);

  const addLog = (message: string, type: BuildLog['type'] = 'info') => {
    setLogs(prev => [...prev, {
      id: Math.random().toString(36).substring(7),
      message,
      type,
      timestamp: Date.now()
    }]);
  };

  const handleGenerate = async () => {
    if (!config.appName) {
      alert("الرجاء إدخال اسم التطبيق");
      return;
    }

    setStatus(AppStatus.GENERATING_CODE);
    setLogs([]);
    addLog(`Starting project initialization for ${config.packageName}...`);
    addLog(`Selected Primary Color: ${config.primaryColor}`);
    
    try {
      addLog("Contacting Gemini AI to generate React Native architecture...", 'info');
      
      // Call Gemini Service
      const files = await generateAppCode(config);
      setGeneratedFiles(files);
      
      addLog("Source code generated successfully.", 'success');
      
      // Start Simulation of Build
      setStatus(AppStatus.BUILDING);
      simulateBuildProcess();

    } catch (error) {
      console.error(error);
      addLog("Failed to generate code from AI model.", 'error');
      setStatus(AppStatus.ERROR);
    }
  };

  const simulateBuildProcess = () => {
    const steps = [
      "Resolving dependencies...",
      "Linking native modules...",
      "Compiling Java sources...",
      "Transforming JavaScript bundles...",
      "Optimizing assets...",
      "Signing APK with debug key...",
      "WARNING: Browser environment detected. Skipping native binary compilation.",
      "Generating simulation package...",
      "Build Successful! APK generated: app-debug.apk"
    ];

    let delay = 0;
    steps.forEach((step, index) => {
      delay += Math.random() * 1000 + 800; // Random delay between 800ms and 1800ms
      setTimeout(() => {
        let type: BuildLog['type'] = 'info';
        if (step.includes('WARNING')) type = 'warning';
        if (index === steps.length - 1) type = 'success';
        
        addLog(step, type);
        if (index === steps.length - 1) {
          setStatus(AppStatus.COMPLETED);
        }
      }, delay);
    });
  };

  const downloadSourceCode = () => {
    const element = document.createElement("a");
    const fileContent = JSON.stringify(generatedFiles, null, 2);
    const file = new Blob([fileContent], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `${config.appName.replace(/\s+/g, '_')}_source.json`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadApkClick = () => {
    setShowApkAlert(true);
  };

  const proceedDownloadAPK = () => {
    setShowApkAlert(false);
    const element = document.createElement("a");
    // Create a dummy APK content text
    const fileContent = `
    تنبيه: هذا ليس تطبيقاً حقيقياً!
    WARNING: THIS IS NOT A REAL APK!
    
    This file was generated by a browser-based prototyping tool (APK Builder Studio).
    Browsers cannot compile real Android applications (binary code) directly.
    
    To get a real app:
    1. Download the Source Code (JSON/Zip option) from the website.
    2. Open it in a development environment like Android Studio, VS Code, or Expo.
    3. Run the build command there.
    
    -------------------------
    App Name: ${config.appName}
    Package: ${config.packageName}
    Version: 1.0.0-debug
    Build Time: ${new Date().toISOString()}
    -------------------------
    
    NOTE: If you tried to install this file on a phone, you will see a "Parse Error" because this is just a text file renamed as .apk.
    `;
    
    const file = new Blob([fileContent], {type: 'application/vnd.android.package-archive'});
    element.href = URL.createObjectURL(file);
    element.download = `${config.appName.replace(/\s+/g, '_')}-debug.apk`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    addLog("Simulation APK file downloaded to device.", 'success');
  };

  return (
    <div className="min-h-screen bg-dark text-gray-200 flex flex-col md:flex-row overflow-hidden font-sans">
      
      {/* Sidebar / Configuration (Right Side for RTL) */}
      <div className="w-full md:w-[450px] bg-dark border-l border-gray-800 flex flex-col h-screen z-20 shadow-xl">
        <ConfigurationPanel 
          config={config} 
          setConfig={setConfig} 
          status={status}
          onGenerate={handleGenerate}
        />
      </div>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col h-screen relative bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-gray-800 via-dark to-black">
        
        {/* Header */}
        <header className="h-16 border-b border-gray-800 flex items-center justify-between px-8 bg-dark/50 backdrop-blur-md">
          <div className="flex items-center gap-2">
            <Zap className="text-yellow-400" />
            <span className="font-bold text-xl tracking-wide">APK Builder <span className="text-primary">Studio</span></span>
          </div>
          
          <div className="flex items-center gap-3">
             {(status === AppStatus.COMPLETED || status === AppStatus.BUILDING || status === AppStatus.GENERATING_CODE) && (
                <button 
                  onClick={handleDownloadApkClick}
                  disabled={status !== AppStatus.COMPLETED}
                  className={`px-4 py-1.5 rounded-lg text-sm font-bold flex items-center gap-2 transition-all duration-300 animate-in fade-in
                    ${status === AppStatus.COMPLETED 
                        ? 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg shadow-emerald-500/20 hover:scale-105' 
                        : 'bg-gray-800 text-gray-500 cursor-not-allowed border border-gray-700'}`}
                >
                  <Download size={16} />
                  <span>{status === AppStatus.COMPLETED ? 'تحميل APK' : 'جاري التحضير...'}</span>
                </button>
             )}

             <div className="flex bg-gray-800 rounded-lg p-1">
                <button 
                    onClick={() => setActiveTab('preview')}
                    className={`px-4 py-1.5 rounded-md text-sm transition-all ${activeTab === 'preview' ? 'bg-primary text-white shadow-lg' : 'text-gray-400 hover:text-white'}`}
                >
                    <div className="flex items-center gap-2">
                        <Smartphone size={14} />
                        <span>معاينة</span>
                    </div>
                </button>
                <button 
                    onClick={() => setActiveTab('code')}
                    className={`px-4 py-1.5 rounded-md text-sm transition-all ${activeTab === 'code' ? 'bg-primary text-white shadow-lg' : 'text-gray-400 hover:text-white'}`}
                    disabled={generatedFiles.length === 0}
                >
                    <div className="flex items-center gap-2">
                        <Code size={14} />
                        <span>الكود المصدري</span>
                    </div>
                </button>
             </div>
          </div>
        </header>

        {/* Workspace */}
        <main className="flex-1 overflow-hidden relative p-8 flex flex-col items-center">
            
            {activeTab === 'preview' && (
                <div className="h-full w-full flex flex-col items-center justify-center animate-fadeIn">
                    <MobilePreview config={config} loading={status === AppStatus.GENERATING_CODE} />
                </div>
            )}

            {activeTab === 'code' && (
                <div className="w-full h-full bg-[#1e1e1e] rounded-xl border border-gray-700 overflow-hidden flex flex-col animate-fadeIn">
                    <div className="bg-[#252526] px-4 py-2 border-b border-black flex justify-between items-center">
                        <span className="text-sm text-gray-300">Generated Files</span>
                        <button onClick={downloadSourceCode} className="text-xs flex items-center gap-1 text-primary hover:text-white transition-colors">
                            <Download size={12} /> تحميل JSON
                        </button>
                    </div>
                    <div className="flex-1 overflow-y-auto p-4">
                        {generatedFiles.map((file, idx) => (
                            <div key={idx} className="mb-8">
                                <h3 className="text-yellow-500 font-mono text-sm mb-2">{'//'} {file.fileName}</h3>
                                <pre className="font-mono text-xs text-gray-300 bg-black/30 p-4 rounded-lg overflow-x-auto border border-gray-800">
                                    <code>{file.code}</code>
                                </pre>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Terminal Overlay */}
            <div className={`absolute bottom-8 left-8 right-8 transition-all duration-500 transform ${status !== AppStatus.IDLE ? 'translate-y-0 opacity-100' : 'translate-y-[120%] opacity-0'}`}>
                <BuildTerminal logs={logs} isVisible={true} />
            </div>

        </main>

        {/* Disclaimer Footer */}
        <footer className="py-2 text-center text-[10px] text-gray-600 border-t border-gray-800">
            تم الإنشاء بواسطة Gemini AI • هذا نموذج محاكاة وليس مترجم APK حقيقي (Browser Simulation)
        </footer>

        {/* APK Warning Dialog */}
        {showApkAlert && (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
                <div className="bg-dark-light border border-gray-700 rounded-2xl p-6 max-w-md w-full text-center shadow-2xl relative animate-in zoom-in-95 duration-200">
                    <button onClick={() => setShowApkAlert(false)} className="absolute top-4 right-4 text-gray-400 hover:text-white">
                        <X size={20} />
                    </button>
                    <div className="w-16 h-16 bg-yellow-500/10 rounded-full flex items-center justify-center mx-auto mb-4 border border-yellow-500/20">
                        <AlertTriangle size={32} className="text-yellow-500" />
                    </div>
                    <h3 className="text-xl font-bold text-white mb-2">تنبيه: ملف محاكاة</h3>
                    <p className="text-gray-300 text-sm mb-6 leading-relaxed">
                        أنت تحاول تحميل ملف APK تم إنشاؤه داخل المتصفح. 
                        <br/>
                        <span className="text-red-400 font-bold">هذا الملف لن يعمل على هاتفك</span> وسيظهر خطأ "مشكلة في تحليل الحزمة" لأنه ملف وهمي. المتصفحات لا يمكنها بناء تطبيقات أندرويد حقيقية.
                    </p>
                    <div className="flex gap-3 flex-col sm:flex-row">
                        <button onClick={proceedDownloadAPK} className="flex-1 px-4 py-3 rounded-xl border border-gray-600 text-gray-400 hover:bg-gray-800 text-sm transition-colors">
                            تحميل الملف الوهمي
                        </button>
                        <button onClick={() => { setShowApkAlert(false); downloadSourceCode(); }} className="flex-1 px-4 py-3 rounded-xl bg-primary hover:bg-emerald-600 text-white font-bold text-sm shadow-lg transition-colors flex items-center justify-center gap-2">
                            <Code size={16} />
                            تحميل الكود المصدري
                        </button>
                    </div>
                    <p className="mt-4 text-[10px] text-gray-500">للمبرمجين: استخدم الكود المصدري في Android Studio لبناء APK حقيقي.</p>
                </div>
            </div>
        )}

      </div>
    </div>
  );
};

export default App;